# Generated by GitHub Copilot
"""将独立 message 表收敛为 conversation.messages JSONB。"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260807_01"
down_revision: str | Sequence[str] | None = "20260806_03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """按消息 ID 保序内嵌历史消息，并删除独立 message 表。"""
    op.add_column(
        "conversation",
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )

    op.execute(
        """
        UPDATE conversation AS conversation_row
        SET messages = COALESCE(
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'role', message_row.role,
                        'content', message_row.text
                    )
                    ORDER BY message_row.id
                )
                FROM message AS message_row
                WHERE message_row.conversation_id = conversation_row.id
            ),
            '[]'::jsonb
        )
        """
    )
    op.execute("UPDATE conversation SET user_id = '01' WHERE user_id <> '01'")
    op.create_check_constraint(
        "ck_conversation_user_id",
        "conversation",
        "user_id = '01'",
    )
    op.drop_index("ix_message_conversation_id", table_name="message")
    op.drop_table("message")


def downgrade() -> None:
    """从 JSONB 数组恢复独立 message 表。"""
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), autoincrement=True, primary_key=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system')",
            name="ck_message_role",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_message_conversation_id", "message", ["conversation_id"])
    op.execute(
        """
        INSERT INTO message (conversation_id, role, text)
        SELECT
            conversation_row.id,
            message_row.value ->> 'role',
            message_row.value ->> 'content'
        FROM conversation AS conversation_row
        CROSS JOIN LATERAL jsonb_array_elements(conversation_row.messages)
            WITH ORDINALITY AS message_row(value, position)
        ORDER BY conversation_row.created_at, conversation_row.id, message_row.position
        """
    )
    op.drop_constraint(
        "ck_conversation_user_id",
        "conversation",
        type_="check",
    )
    op.drop_column("conversation", "messages")
