# Generated by GitHub Copilot
import json
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Literal, TypedDict

import httpx

from src.core.config import get_settings
from src.core.errors import AppError


class AIMessageInput(TypedDict):
    """SiliconFlow Chat Completions 接受的单条上下文消息。"""

    role: Literal["user", "assistant", "system"]
    content: str


@dataclass(frozen=True, slots=True)
class AIStreamChunk:
    """统一表示模型输出的推理或正文增量。"""

    kind: Literal["reasoning", "content"]
    delta: str


class SiliconFlowError(Exception):
    """表示 SiliconFlow 请求失败或流未完整结束。"""


class SiliconFlowClient:
    """通过 SiliconFlow 的 OpenAI 兼容接口异步生成流式回答。"""

    def __init__(
        self,
        *,
        api_key: str,
        base_url: str,
        model: str,
        temperature: float,
        max_tokens: int,
    ) -> None:
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens

    async def stream_chat(
        self, messages: list[AIMessageInput]
    ) -> AsyncIterator[AIStreamChunk]:
        """解析上游 SSE，只在收到 [DONE] 时视为完整响应。"""
        timeout = httpx.Timeout(300.0, connect=10.0)
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "stream": True,
        }

        try:
            async with (
                httpx.AsyncClient(timeout=timeout) as client,
                client.stream(
                    "POST",
                    f"{self.base_url}/chat/completions",
                    headers=headers,
                    json=payload,
                ) as response,
            ):
                if response.is_error:
                    await response.aread()
                    raise SiliconFlowError(
                        f"SiliconFlow returned HTTP {response.status_code}"
                    )

                async for line in response.aiter_lines():
                    if not line.startswith("data:"):
                        continue
                    data = line.removeprefix("data:").strip()
                    if data == "[DONE]":
                        return
                    if not data:
                        continue

                    chunk = json.loads(data)
                    choices = chunk.get("choices") or []
                    if not choices:
                        continue
                    delta = choices[0].get("delta") or {}
                    reasoning = delta.get("reasoning_content")
                    content = delta.get("content")
                    if reasoning:
                        yield AIStreamChunk(kind="reasoning", delta=reasoning)
                    if content:
                        yield AIStreamChunk(kind="content", delta=content)
        except (httpx.HTTPError, json.JSONDecodeError) as exc:
            raise SiliconFlowError("SiliconFlow stream failed") from exc

        raise SiliconFlowError("SiliconFlow stream ended before [DONE]")


def get_siliconflow_client() -> SiliconFlowClient:
    """从环境配置创建 SiliconFlow 客户端。"""
    settings = get_settings()
    if not settings.siliconflow_api_key:
        raise AppError(
            code="AI_NOT_CONFIGURED",
            message="SiliconFlow API key is not configured",
            status_code=503,
        )
    return SiliconFlowClient(
        api_key=settings.siliconflow_api_key,
        base_url=settings.siliconflow_base_url,
        model=settings.siliconflow_model,
        temperature=settings.siliconflow_temperature,
        max_tokens=settings.siliconflow_max_tokens,
    )
